name: sorter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - seaborn=0.12.1
  - streamlit=1.18.0
  - numpy=1.23.4
  - matplotlib=3.6.0
  - scipy=1.9.3
  - pyserial=3.5
  - altair=4.0
  - plotly=5.19.*
  - jupyterlab=3.5.*